name: 🐛 Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission checklist
      description: Please verify these items before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I am using the latest version of furs-client-ts
          required: true
        - label: I have read the documentation
          required: true

  - type: input
    id: version
    attributes:
      label: Package Version
      description: What version of furs-client-ts are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Tell us what happened!
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Initialize FursClient with...
        2. Call method...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened instead
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: Code Example
      description: Please provide a minimal code example that reproduces the issue
      render: typescript
      placeholder: |
        import { FursClient } from 'furs-client-ts';
        
        const client = new FursClient({
          // your config
        });
        
        // code that causes the bug

  - type: textarea
    id: error-message
    attributes:
      label: Error Message/Stack Trace
      description: If applicable, add error messages or stack traces
      render: text

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment are you using?
      options:
        - FURS Test Environment
        - FURS Production Environment
        - Local Development
        - Other
    validations:
      required: true

  - type: textarea
    id: system-info
    attributes:
      label: System Information
      description: Please provide system details
      placeholder: |
        - OS: [e.g. Windows 11, macOS 12.6, Ubuntu 20.04]
        - Node.js version: [e.g. 18.17.0]
        - TypeScript version: [e.g. 5.0.4]
        - Package manager: [npm/yarn/pnpm]
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (certificate type, network setup, etc.)
